apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apunta al directorio base
bases:
  - ../../base

namespace: dev

# Parches para modificar la base
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: poc-rest-api
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: poc-rest-api
