# Workflow de CI/CD que construye, despliega a 'dev', espera por una
# aprobación manual, y luego promueve el lanzamiento a 'prod'.

name: Deploy to Dev and Promote to Prod

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy_dev:
    name: Build and Deploy to Dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    outputs:
      image_name: ${{ steps.image-data.outputs.image_name }}
      image_version: ${{ steps.image-data.outputs.image_version }}
      stable_image_version: ${{ steps.image-data.outputs.stable_image_version }}
      git_tag: ${{ steps.image-data.outputs.git_tag }}
      stable_git_tag: ${{ steps.image-data.outputs.stable_git_tag }}
      is_rc: ${{ steps.image-data.outputs.is_rc }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        id: go

      - name: Extract and Correct Image/Tag Info
        id: image-data
        run: |
          IMAGE_FULL=$(grep 'image:' deploy/overlays/dev/patch-deployment.yaml | awk '{print $2}')
          if [ -z "$IMAGE_FULL" ]; then
            echo "Error: No se pudo encontrar la línea 'image:' en deploy/overlays/dev/patch-deployment.yaml"
            exit 1
          fi

          IMAGE_NAME=$(echo $IMAGE_FULL | cut -d':' -f1)
          RAW_IMAGE_VERSION=$(echo $IMAGE_FULL | cut -d':' -f2)

          # --- LÓGICA DE CORRECCIÓN ---
          # Asegura que el formato sea X.Y.Z-rc.N
          CORRECTED_IMAGE_VERSION=$RAW_IMAGE_VERSION
          if [[ "$RAW_IMAGE_VERSION" == *"rc"* && "$RAW_IMAGE_VERSION" != *"rc."* ]]; then
            # Si dice 'rc' pero no 'rc.', le insertamos el punto.
            CORRECTED_IMAGE_VERSION=$(echo "$RAW_IMAGE_VERSION" | sed 's/rc/rc./')
            echo "Formato de versión corregido de '$RAW_IMAGE_VERSION' a '$CORRECTED_IMAGE_VERSION'"
          fi
          # --- FIN LÓGICA DE CORRECCIÓN ---

          GIT_TAG="v${CORRECTED_IMAGE_VERSION}"
          STABLE_IMAGE_VERSION=$(echo $CORRECTED_IMAGE_VERSION | sed 's/-.*//')
          STABLE_GIT_TAG="v${STABLE_IMAGE_VERSION}"

          IS_RC="false"
          if [[ "$CORRECTED_IMAGE_VERSION" == *"-rc."* ]]; then
            IS_RC="true"
          fi

          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "image_version=$CORRECTED_IMAGE_VERSION" >> $GITHUB_OUTPUT
          echo "stable_image_version=$STABLE_IMAGE_VERSION" >> $GITHUB_OUTPUT
          echo "git_tag=$GIT_TAG" >> $GITHUB_OUTPUT
          echo "stable_git_tag=$STABLE_GIT_TAG" >> $GITHUB_OUTPUT
          echo "is_rc=$IS_RC" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.image-data.outputs.image_name }}:${{ steps.image-data.outputs.image_version }}

      - name: Create and push Git tag for Dev
        if: success()
        run: |
          GIT_TAG=${{ steps.image-data.outputs.git_tag }}
          if git rev-parse -q --verify "refs/tags/$GIT_TAG" >/dev/null; then
            echo "El tag $GIT_TAG ya existe. No se tomará ninguna acción."
          else
            echo "Creando y subiendo el tag anotado $GIT_TAG..."
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            git tag -a -m "Release Candidate ${GIT_TAG}" "${GIT_TAG}"
            git push origin "${GIT_TAG}"
            echo "Git tag para Dev: ${GIT_TAG} creado y subido."
          fi

  approve_for_production:
    name: Approve for Production
    runs-on: ubuntu-latest
    needs: build_and_deploy_dev
    if: needs.build_and_deploy_dev.outputs.is_rc == 'true'
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Awaiting Production Approval
        run: echo "Esperando aprobación para promover la versión estable ${{ needs.build_and_deploy_dev.outputs.stable_git_tag }} a producción."

  deploy_prod:
    name: Tag and Deploy to Prod
    runs-on: ubuntu-latest
    needs: [build_and_deploy_dev, approve_for_production]
    if: always() && needs.approve_for_production.result == 'success'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag and Push Stable Image
        run: |
          docker pull ${{ needs.build_and_deploy_dev.outputs.image_name }}:${{ needs.build_and_deploy_dev.outputs.image_version }}
          docker tag ${{ needs.build_and_deploy_dev.outputs.image_name }}:${{ needs.build_and_deploy_dev.outputs.image_version }} ${{ needs.build_and_deploy_dev.outputs.image_name }}:${{ needs.build_and_deploy_dev.outputs.stable_image_version }}
          docker push ${{ needs.build_and_deploy_dev.outputs.image_name }}:${{ needs.build_and_deploy_dev.outputs.stable_image_version }}

      - name: Create and push Git tag for Prod
        if: success()
        run: |
          STABLE_GIT_TAG=${{ needs.build_and_deploy_dev.outputs.stable_git_tag }}
          if git rev-parse -q --verify "refs/tags/$STABLE_GIT_TAG" >/dev/null; then
            echo "El tag $STABLE_GIT_TAG ya existe. No se tomará ninguna acción."
          else
            echo "Creando y subiendo el tag anotado $STABLE_GIT_TAG..."
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            git tag -a -m "Stable Release ${STABLE_GIT_TAG}" "${STABLE_GIT_TAG}"
            git push origin "${STABLE_GIT_TAG}"
            echo "Git tag para Prod: ${STABLE_GIT_TAG} creado y subido."
          fi
